KernelFunction Class Reference
#include <kernelFunction.h>
Public Member Functions
double kernelFunction (vector< double >)
vector< double > kernelGradient (vector< double >)
Member Function Documentation
double KernelFunction::kernelFunction (vector< double > r)
References H, normOf(), and W.
Referenced by SPHEquation::entropyStar(), and TEST().
                                                      {
    double a;
    double q;
    a = normOf(r);
    q = a/H;
    if (q > 2)
        return 0;
    if (q >= 1)
        return W * 0.25 * (pow(2 - q, 3));
    return W * (1 - (1.5 * q * q) + (0.75 * q * q * q));
}
vector< double > KernelFunction::kernelGradient (vector< double > r)
References GRAD_W, H, and normOf().
Referenced by SPHEquation::dMomentum_dTau().
                                                               {
    double a = normOf(r);
    double q = a/H;
    vector<double> zero (2, 0.0);
    vector<double> oneOverR(2, 0.0);
    for(int i = 0; i < 2; i++)
      oneOverR[i] = 1/(r[i]);
    if (q > 2)
        return zero;
    if (q > 1)
        return ((GRAD_W / a) * (2 - q) * (2 - q)) * r;
    return (GRAD_W_2 * (-3 + 9 * q/4.)) * r;
}
The documentation for this class was generated from the following files:
/Users/rafael/Dropbox/sphene/src/kernelFunction.h
/Users/rafael/Dropbox/sphene/src/kernelFunction.cpp