SPHParticle Class Reference
#include <sphParticle.h>
Public Member Functions
SPHParticle ()
bool hasLeftParticle ()
bool hasRightParticle ()
bool hasUpParticle ()
bool hasDownParticle ()
double Gamma ()
void CalculateEntropyDensity (double)
Public Attributes
vector< double > velocity
vector< double > position
vector< double > momentum
vector< double > dMomentum_dTau
double energyDensity
double entropyDensity
double entropyDensityWeight
double pressureDensity
EquationOfMotion equationOfMotion
SPHParticle * leftParticle
SPHParticle * rightParticle
SPHParticle * upParticle
SPHParticle * downParticle
Constructor & Destructor Documentation
SPHParticle::SPHParticle ()
References velocity().
{
  velocity.resize(2);
  velocity[0] = 0.0;
  velocity[1] = 0.0;
  position.resize(2);
  momentum.resize(2);
  dMomentum_dTau.resize(2);
}
Member Function Documentation
void SPHParticle::CalculateEntropyDensity (double entropyStar)
s = {s^{*}}{{-g} }
{
  entropyDensity = entropyStar/Gamma();
}
double SPHParticle::Gamma ()
References normOf(), and velocity().
Referenced by SPHEquation::dMomentum_dTau().
{
  double vAux = normOf(velocity);
  return (1/sqrt(1.0 - (vAux*vAux)));
}
bool SPHParticle::hasDownParticle ()
bool SPHParticle::hasLeftParticle ()
bool SPHParticle::hasRightParticle ()
bool SPHParticle::hasUpParticle ()
Member Data Documentation
vector<double> SPHParticle::dMomentum_dTau
SPHParticle* SPHParticle::downParticle
double SPHParticle::energyDensity
Thermodynamic variables
Referenced by TEST().
double SPHParticle::entropyDensity
Referenced by SPHEquation::dMomentum_dTau().
double SPHParticle::entropyDensityWeight
Referenced by SPHEquation::dMomentum_dTau().
EquationOfMotion SPHParticle::equationOfMotion
SPHParticle* SPHParticle::leftParticle
vector<double> SPHParticle::momentum
vector<double> SPHParticle::position
Referenced by SPHEquation::dMomentum_dTau(), SPHEquation::entropyStar(), and TEST().
double SPHParticle::pressureDensity
Referenced by SPHEquation::dMomentum_dTau().
SPHParticle* SPHParticle::rightParticle
SPHParticle* SPHParticle::upParticle
vector<double> SPHParticle::velocity
Dynamic variables
The documentation for this class was generated from the following files:
/Users/rafael/Dropbox/sphene/src/sphParticle.h
/Users/rafael/Dropbox/sphene/src/sphParticle.cpp