SPHEquation Class Reference
#include <sphEquation.h>
Public Member Functions
SPHEquation ()
double entropyStar (SPHParticle, vector< SPHParticle >, KernelFunction)
vector< double > dMomentum_dTau (SPHParticle, vector< SPHParticle >, KernelFunction, double)
Constructor & Destructor Documentation
SPHEquation::SPHEquation ()
{
}
Member Function Documentation
vector< double > SPHEquation::dMomentum_dTau (SPHParticle sphParticle, vector< SPHParticle > listOfParticles, KernelFunction w, double tau)
References SPHParticle::entropyDensity, SPHParticle::entropyDensityWeight, SPHParticle::Gamma(), KernelFunction::kernelGradient(), SPHParticle::position, and SPHParticle::pressureDensity.
Referenced by TEST().
{
  vector<double> result (2, 0.0);
  vector<double> r (2, 0.0);
  for(int i = 0; i < listOfParticles.size(); i++)
  {
    r = sphParticle.position - listOfParticles[i].position;
    result[0] += (sphParticle.entropyDensityWeight * listOfParticles[i].
      entropyDensityWeight) * (sphParticle.pressureDensity/pow((sphParticle.Gamma() * sphParticle.
      entropyDensity), 2) + (listOfParticles[i].pressureDensity/pow((listOfParticles[i].Gamma() *
      listOfParticles[i].entropyDensity), 2))) * w.kernelGradient(r)[0];
    result[1] += (sphParticle.entropyDensityWeight * listOfParticles[i].
      entropyDensityWeight) * (sphParticle.pressureDensity/pow((sphParticle.Gamma() * sphParticle.
      entropyDensity), 2) + (listOfParticles[i].pressureDensity/pow((listOfParticles[i].Gamma() *
      listOfParticles[i].entropyDensity), 2))) * w.kernelGradient(r)[1];
  }
  return -(1/tau) * result;
}
double SPHEquation::entropyStar (SPHParticle sphParticle, vector< SPHParticle > listOfParticles, KernelFunction w)
: list of SPHParticles, KernelFunction (x-x_j)
References KernelFunction::kernelFunction(), and SPHParticle::position.
Referenced by TEST().
{
  double entropyStar = 0.0;
  vector<double> r (2, 0.0);
  for(int i = 0; i < listOfParticles.size(); i++)
  {
    r = sphParticle.position - listOfParticles[i].position;
    entropyStar += listOfParticles[i].entropyDensityWeight * w.kernelFunction(r);
  }
  return entropyStar;
}
The documentation for this class was generated from the following files:
/Users/rafael/Dropbox/sphene/src/sphEquation.h
/Users/rafael/Dropbox/sphene/src/sphEquation.cpp