IdealEquationOfState Class Reference
The class of the ``ideal" equation of state: $p = \frac{\epsilon}{3}$.
#include <idealEquationOfState.h>
Public Member Functions
double calculatePressureDensity (double)
Function that returns pressure density in function of entropy density : $p(s)$.
double calculateEnergyDensity (double)
Function that returns energy density in function of entropy density : $\epsilon(s)$.
double calculateEntropyDensity (double)
Function that returns entropy density in function of energy density : $s(\epsilon)$.
Detailed Description
The class of the ``ideal" equation of state: $p = \frac{\epsilon}{3}$.
Member Function Documentation
double IdealEquationOfState::calculateEnergyDensity (double EntropyDensity)
Function that returns energy density in function of entropy density : $\epsilon(s)$.
Parameters
EntropyDensity
Referenced by TEST().
{
  return pow(EntropyDensity/2.43, 1.333333333);/*_PI * _PI * 47.5 * pow((15.0 * EntropyDensity)/(_PI * _PI
      * 47.5), 1.3333333333) / 30.0;*/
}
double IdealEquationOfState::calculateEntropyDensity (double EnergyDensity)
Function that returns entropy density in function of energy density : $s(\epsilon)$.
Parameters
EnergyDensity
Referenced by TEST().
{
  return 2.43 * pow(EnergyDensity, 0.75);
  /*_PI * _PI * 47.5 * pow((30.0 * EnergyDensity)/(_PI * _PI * 47.5), 0.75)/15.0;*/
}
double IdealEquationOfState::calculatePressureDensity (double EntropyDensity)
Function that returns pressure density in function of entropy density : $p(s)$.
Parameters
EntropyDensity
Referenced by TEST().
{
  return calculateEnergyDensity(EntropyDensity)/3.0;/*_PI * _PI * 47.5 * pow((15.0 *
       EntropyDensity)/(_PI * _PI * 47.5), 1.333333333) / 30.0;*/
}
The documentation for this class was generated from the following files:
/Users/rafael/Dropbox/sphene/src/idealEquationOfState.h
/Users/rafael/Dropbox/sphene/src/idealEquationOfState.cpp