/Users/rafael/Dropbox/sphene/src/vector.h File Reference
#include <iostream>
*
#include <cstdlib>
*
#include <cstdio>
*
#include <vector>
*
#include <cmath>
*
Functions
vector< double > operator+ (const vector< double > &, const vector< double > &)
vector< double > operator- (const vector< double > &, const vector< double > &)
vector< double > operator* (const double &, const vector< double > &)
double operator* (const vector< double > &, const vector< double > &)
double normOf (const vector< double > &)
Function Documentation
double normOf (const vector< double > &)
Function to calculates the norm of a vector
Referenced by SPHParticle::Gamma(), KernelFunction::kernelFunction(), and KernelFunction::kernelGradient().
{
  double size = r.size();
  double sum = 0.0;
  for(int i = 0; i < size; i++)
    sum += r[i] * r[i];
  return sqrt(sum);
}
vector<double> operator* (const double & , const vector< double > &)
Overloading the times (*) operator to define the multiplication of a escalar (double) and a vector.
{
  vector<double> result(x.size());
  for (int i = 0; i < x.size(); i++)
    result[i] = K * x[i];
  return result;
}
double operator* (const vector< double > & , const vector< double > &)
Overloading the times(*) operator to define the escalar product between two vectors.
{
  double result = 0;
  if (a.size() != b.size()){
    cerr << "Vector innerProduct Error: Vectors with different dimensions!";
    exit(-1);
  }
  for (int i = 0; i < a.size(); i++)
    result += a[i] * b[i];
  return result;
}
vector<double> operator+ (const vector< double > & , const vector< double > &)
Overloading the plus (+) operator to define the summation of two vectors.
{
  double size;
  size = r1.size();
  if(r1.size() != r2.size()) {
    cerr << "Vector Sumation Error: Vectors with different dimensions!";
    exit(-1);
  }
  vector<double> r3 (size,0);
  for(int i = 0; i < int(r3.size()); i++)
    r3[i] = r1[i] + r2[i];
  return r3;
}
vector<double> operator- (const vector< double > & , const vector< double > &)
Overloading the minus (-) operator to define the subtraction of two vectors.
{
  double size;
  size = r1.size();
  if(r1.size() != r2.size()) {
    cerr << "Vector Subtraction Error: Vectors with different dimensions!";
    exit(-1);
  }
  vector<double> r3 (size,0);
  for(int i = 0; i < int(r3.size()); i++)
    r3[i] = r1[i] - r2[i];
  return r3;
}